repository: MoTec95/MoTec95.github.io
repository_url: https://github.com/MoTec95/MoTec95.github.io

weixin_url: https://mp.weixin.qq.com/profile?src=3&ver=1&signature=YP--JzBH8dFqS50D4TsMuOcSHOuOVbJFtz6bJedvQAuD5LJHmQb8roqRR1o3Nfdp37YT3aeYL2L2K1zToNAA1g==

timezone: Asia/Shanghai
lang: zh_CN

title: MoTec
alias_en: MoTec
alias_cn: MoTec
description: A Navigation Website for MoTec
keywords: MoTec-Navi, MoTec, BUPT, Navi, Navigation,导航,流量,公众号,技术,理财
url: https://motec95.github.io
established_at: "2019-3-18T00:00+08:00"

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor